CREATE TABLE PERSON_TBL(
 ID NUMBER PRIMARY KEY ,
 NAME NVARCHAR2(20),
 FAMILY NVARCHAR2(20)
);

CREATE SEQUENCE PERSON1_SEQ START WITH 1 INCREMENT BY 1;


CREATE TABLE PRODUCT_TBL(
  ID NUMBER PRIMARY KEY ,
  NAME NVARCHAR2(30),
  BRAND NVARCHAR2(20),
  PRICE NUMBER,
  COUNT NUMBER,
  OWNER_ID REFERENCES PERSON_TBL
);

CREATE SEQUENCE PRODUCT_SEQ START WITH 1 INCREMENT BY 1;

CREATE VIEW PRODUCT_OWNER_REPORT AS
    SELECT PE.ID   AS OWNER_ID,
           PE.NAME AS PERSON_NAME,
           PE.FAMILY AS PERSON_FAMILY,
           PR.ID     AS PRODUCT_ID,
           PR.BRAND  AS PRODUCT_BRAND,
           PR.PRICE  AS PRODUCT_PRICE,
           PR.COUNT  AS PRODUCT_COUNT
FROM PERSON_TBL PE
JOIN PRODUCT_TBL PR
ON PE.ID = PR.OWNER_ID;

COMMIT;
