CREATE TABLE PERSON(
    ID NUMBER PRIMARY KEY,
    NAME NVARCHAR2(30),
    FAMILY NVARCHAR2(30),
    GENDER NVARCHAR2(6),
    BIRTH_DATE DATE,
    CITY NVARCHAR2(20),
    SE_SKILL NUMBER(1),
    EE_SKILL NUMBER(1)
 );

 CREATE SEQUENCE PERSON_SEQ START WITH 1 INCREMENT BY 1;